### ISSUE TITLE
Vercel deployment failed

### ISSUE THREAD

**Issue by ahmadjonhn** [sandstreamdev/react-swipeable-list#180]
| Failed to compile.
-- | --
21:14:04.610 | ModuleNotFoundError: Module not found: Error: Can't resolve '@sandstreamdev/react-swipeable-list' in '/vercel/workpath0/pages'
21:14:04.610 | > Build error occurred
21:14:04.612 | Error: > Build failed because of webpack errors
21:14:04.612 | at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
21:14:04.612 | at runMicrotasks (<anonymous>)
21:14:04.612 | at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by evanezcent** [comment]
had the same problem, does anyone know how to solve this problem?

**Comment by marekrozmus** [comment]
Could you please provide some minimal repository with configuration that I could reproduce this issue?
